
# Sitewide variables
title: The Orifon Family
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  This website is devoted to two great poets, writers and public figures:
  Orif Gulkhany and Olimzhon Orify, and their descendants.
baseurl: ""
url: "http://orifon.com"

# Social links
github_username: karipov
wikipedia_ru: Дом-музей_Орифа_Гульхани
wikipedia_page_name: Home-Museum

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Header settings
header_pages:
  - official_documents.md
  - publications.md
  - history.md
  - multimedia.md

# Analytics
google_analytics: UA-108885235-2
