
# Sitewide variables
title: The Orifon Family
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  This website is devoted to two great poets, writers and public figures:
  Orif Gulkhany and Olimzhon Orify, and their descendants.
baseurl: ""
url: "http://orifon.com"
github_username: karipov

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Header settings
header_pages:
  - history.md
  - official_documents.md
  - publications.md
  - history.md
  - multimedia.md
